### ISSUE TITLE
Investigate Candidates for Mod Addition

### ISSUE THREAD

**Issue by eighteenAM** [MJCSStudios/1AQCraft#10]
- Immersive Petroleum
  - Simple, lightweight bolt-on for Immersive Engineering
  - Adds oil deposits thru IE's per-chunk "virtual" ore deposit mechanic
  - With BuildCraft oil disabled and Magneticraft a candidate for removal, ensures reasonable access to oil, without the mess
- Buildcraft Core, Compat, Factory, Builders, Energy
  - Recommend installing only those BC modules that we need. #8 
  - BC Silicon is Satan.  It adds 41 pages of items to JEI on a 1440p screen.
- Drugs and Pills
  - Ian will mess with this instead of causing nuclear disasters in his basement

**Comment by TheRealDelkaz** [comment]
Sounds fine, except Drugs and Pills, that will not be added.

**Comment by eighteenAM** [comment]
Ian will be devastated!

**Comment by eighteenAM** [comment]
Immersive Petroleum; BC modules to be added to modpack.
