### ISSUE TITLE
Eliminate duplicate ore, blocks, ingots, etc.

### ISSUE THREAD

**Issue by mskurnik** [MJCSStudios/1AQCraft#2]

**Comment by TheRealDelkaz** [comment]
Duplicate ore from NuclearCraft, Tinker's Construct disabled.

**Comment by eighteenAM** [comment]
Removed all world oregen for Extreme Reactors and Immersive Engineering.  Disabled duplicate ores from Magneticraft.  See [this](https://github.com/MJCSStudios/1AQCraft/commit/82f8861d5cbb5151333904836a76b2b253a8f79f) commit.

**Comment by eighteenAM** [comment]
Blocks, ingots etc. seem to be mostly sorted by the configs themselves.  Most prefer Thermal Expansion items where possible, and some priority tweaks have been made to push others (IE, NuclearCraft) lower except where their items are unique.

**Comment by eighteenAM** [comment]
Redundant (and flammable) Railcraft ores disabled.  Zinc, Saltpeter, and Sulfur ores still enabled.  Oregen left enabled to allow generation of stone variants (Quarried, Sandy, etc.)
