### ISSUE TITLE
Disable Bats

### ISSUE THREAD

**Issue by TheRealDelkaz** [MJCSStudios/1AQCraft#7]
Mitchell don't forget to disable these annoying, rage inducing, horrible little punks.

**Comment by TheRealDelkaz** [comment]
You will fix it.

**Comment by mskurnik** [comment]
`ForgeEssentials` added.  @TheRealDelkaz, please configure FE to disable bats.

**Comment by mskurnik** [comment]
This must be done in-game with the server setup using permissions `fe.protection.mobspawn.natural.Bat` and setting it to false.

**Comment by eighteenAM** [comment]
Bats ACTUALLY disabled now.
