### ISSUE TITLE
Investigate Candidates for Mod Removal

### ISSUE THREAD

**Issue by eighteenAM** [MJCSStudios/1AQCraft#8]
Mods whose purpose for inclusion has been partially or fully supplanted by other mods:
- Netherending Ores
  - Most nether ores now included by CoFH (Nether Foundation).  Nether gemstone ores are probably not needed.
  - End versions of ores are still unique to this mod.  Are they useful?  Do we care?
  - **Overworld Quartz Ore** is unique to this mod.  It might suck to lose it.  Or we might just have to get over it and go to the Nether once in a while.
- Gemmary
  - Adds gems?  That's it?
  - Biomes o' Plenty adds gems.  And ores to get them!
- Magneticraft
  - Interesting methods for energy generation are largely provided in concept by other mods in the pack now.
  - Other major mods (notably CoFH mods) are better for early game, so Magneticraft's new early game not really needed.

Mods which should be installed in a different way:
- Buildcraft
  - There is a modular installation available.  Suggest using it instead, allowing selection of desired modules. #10

**Comment by eighteenAM** [comment]
Gemmary removed because, in addition to gems, it added server crashes.

**Comment by TheRealDelkaz** [comment]
These can all be removed. There are, however, more that are even more unnecessary than these that should be higher on the priority list to axe.

**Comment by eighteenAM** [comment]
I'm all ears for your nominations.

**Comment by TheRealDelkaz** [comment]
Why do we need two separate mods that add guns? For example.

**Comment by eighteenAM** [comment]
I can definitely find and destroy at least one of the mods that adds guns - we don't need more than one thing that adds something as specific as that.  I don't see serious harm in keeping one of them, as long as it isn't insanely OP.

**Comment by eighteenAM** [comment]
Netherending Ores; Magneticraft; Buildcraft (monolithic); Mr Crayfish's Gun Mod to be removed.
